window.OPR_DATA = window.OPR_DATA || {};

window.OPR_DATA.bio = [
  { code: 'BIO130M', name: 'Biología Marina' },
  { code: 'BIO210C', name: 'Biología Computacional' },
  { code: 'BIO225C', name: 'Fisiología y Bioquímica Vegetal' },
  { code: 'BIO249C', name: 'Bioestadística II' },
  { code: 'BIO250M', name: 'Vertebrados Marinos' },
  { code: 'BIO258E', name: 'Práctica Extramural Licenciatura-Track profesional' },
  { code: 'BIO272C', name: 'Farmacología Molecular' },
  { code: 'BIO274E', name: 'Biología y Fisiología Celular' },
  { code: 'BIO277M', name: 'Microbiología Marina' },
  { code: 'BIO295A', name: 'Experiencia de Investigación I' },
  { code: 'BIO295B', name: 'Experiencia de Investigación II' },
  { code: 'BIO295C', name: 'Experiencia de Investigación III (Aprobación especial)' },
  { code: 'BIO296C', name: 'Seminario de Investigación Biológica Licenciatura-Track investigación' },
  { code: 'BIO310A', name: 'Seminario Bibliográfico' },
  { code: 'BIO310B', name: 'Seminario Bibliográfico (B)' },
  { code: 'BIO318E', name: 'Principios de Dinámica Poblacional' },
  { code: 'BIO327M', name: 'Oceanografía Físico Biológica' },
  { code: 'BIO3339', name: 'Bioinformática Avanzada' },
  { code: 'BIO361E', name: 'Neurofisiología' },
  { code: 'BIO380E', name: 'Microbiología Medica' },
  { code: 'BIO389E', name: 'Inmunología Celular y Molecular' },
  { code: 'BIO3920', name: 'Innovación y Emprendimiento en Biotecnología' },
  { code: 'BIO412M', name: 'Socioecología y Conservación Marina' },
  { code: 'BIO420M', name: 'Ecología Marina' },
  { code: 'BIO424C', name: 'Micología' },
  { code: 'BIO428C', name: 'Ecología Química' },
  { code: 'BIO433C', name: 'Parasitología' },
  { code: 'BIO447M', name: 'Fitoplancton Marino' },
  { code: 'EAE105A', name: 'Introducción a la Economía' },
  { code: 'EAE1110', name: 'Introducción a la Microeconomía' },
  { code: 'AGL110',  name: 'Suelos y Fertilidad' },
  { code: 'AGL112',  name: 'Climatología' },
  { code: 'AGL204',  name: 'Principios de Procesamiento, Calidad e Inocuidad de Alimentos' },
  { code: 'AGR205',  name: 'Geomática aplicada a los Recursos Naturales' },
  { code: 'AGE206',  name: 'Introducción a la Economía Ambiental y de los Recursos Naturales' },
  { code: 'AGL211',  name: 'Protección de Plantas' },
  { code: 'AGR212',  name: 'Muestreo y Dinámica de Bosques' },
  { code: 'AGC220',  name: 'Flora Nativa' },
  { code: 'AGC262',  name: 'Manejo del Paisaje' },
  { code: 'AGR308',  name: 'Fauna y Manejo de Vida Silvestre' },
  { code: 'AGR311',  name: 'Manejo de Áreas Protegidas' },
  { code: 'GEO104',  name: 'Geografía Física General' },
  { code: 'GEO3214', name: 'Sistemas de Información Geográfica' },
  { code: 'GEO503',  name: 'Gestión y Administración Territorial' },
  { code: 'GEO609',  name: 'Educación Ambiental para el Desarrollo Sustentable' },
  { code: 'IBM1005', name: 'Introducción a la Ingenieria Biomédica' },
  { code: 'IIC1103', name: 'Introducción a la Programación' },
  { code: 'IIC2233', name: 'Programación Avanzada' },
  { code: 'IIQ2663', name: 'Fundamentos de Biotecnología' },
  { code: 'ICS2813', name: 'Organización y Comportamiento en la Empresa' },
  { code: 'MAT1203', name: 'Algebra Lineal' },
  { code: 'MAT1220', name: 'Cálculo II' },
  { code: 'MEB203B', name: 'Fisiopatología' },
  { code: 'VET0500', name: 'Etología y Bienestar Animal' },
  { code: 'VET111D', name: 'Técnicas Moleculares Aplicadas en Ciencias Animales' },
  { code: 'VET112R', name: 'Biotecnología Reproductiva en Animales Domésticos y Silvestres' },
  { code: 'VET1600', name: 'Salud pública y Epidemiología' },
  { code: 'QIM1018', name: 'Modelos Farmacológicos de Desórdenes Neuropsiquiátricos' },
  { code: 'QIF115A', name: 'Botánica y Farmacognosia' },
  { code: 'QIM450',  name: 'Prevención de Riesgos Profesionales' },
  { code: 'QIM522',  name: 'Especies Reactivas, Antioxidantes y Salud Humana' },
];
